name: dap
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.0=hbb29018_2
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - contourpy=1.3.3=py312hd9148b4_3
  - cycler=0.12.1=pyhd8ed1ab_1
  - dbus=1.13.6=h5008d03_3
  - double-conversion=3.3.1=h5888daf_0
  - expat=2.7.3=h3385a95_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h2c49b7f_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=py312h8a5da7c_0
  - freetype=2.14.1=ha770c72_0
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - graphite2=1.3.14=hecca717_2
  - harfbuzz=9.0.0=hfac3d4d_0
  - icu=73.2=h59595ed_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py312h0a2e395_2
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h0aef613_1
  - libblas=3.11.0=2_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcblas=3.11.0=2_h0358290_openblas
  - libclang-cpp18.1=18.1.8=default_h99862b1_15
  - libclang13=21.1.0=default_h746c552_1
  - libcups=2.3.3=hb8b1518_5
  - libdeflate=1.22=hb9d3cd8_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h69a702a_12
  - libgfortran5=15.2.0=h68bc16d_12
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.80.2=hf974151_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=2_h47877c9_openblas
  - libllvm18=18.1.8=default_hddf928d_9
  - libllvm21=21.1.0=hecd9e04_0
  - libnsl=2.0.0=h5eee18b_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopengl=1.7.0=ha4b6fd6_2
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.51=h421ea60_0
  - libpq=16.11=hc183893_2
  - libsqlite=3.51.0=h0c1763c_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.7.0=he137b08_1
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.11.0=he8b52b9_0
  - libxml2=2.13.9=h2c43086_0
  - libxslt=1.1.43=h7a3aeb2_0
  - libzlib=1.3.1=hb25bd0a_0
  - matplotlib=3.10.8=py312h7900ff3_0
  - matplotlib-base=3.10.8=py312he3d6523_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql-common=8.3.0=h70512c7_5
  - mysql-libs=8.3.0=ha479ceb_5
  - ncurses=6.5=h7934f7d_0
  - numpy=2.3.5=py312h33ff503_0
  - openjpeg=2.5.3=h55fea9a_1
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py312hf79963d_1
  - pcre2=10.43=hcad00b1_0
  - pillow=11.3.0=py312h7b42cdd_3
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pycairo=1.27.0=py312h51b637d_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyside6=6.7.2=py312h91f0f75_4
  - python=3.12.12=hd17a9e1_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=2_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.7.2=h7d13b96_3
  - readline=8.3=hc2a1206_0
  - reportlab=4.4.5=py312h4c3975b_0
  - rlpycairo=0.4.0=pyh6c17108_0
  - scipy=1.16.3=py312h7a1785b_1
  - setuptools=80.9.0=py312h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.2=py312h4c3975b_2
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=17.0.0=py312h4c3975b_1
  - wayland=1.23.1=h3e06ad9_0
  - wheel=0.45.1=py312h06a4308_0
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.6=hb03c661_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.4.0
      - certifi==2025.11.12
      - click==8.3.1
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - fastapi==0.122.0
      - frozenlist==1.8.0
      - greenlet==3.2.4
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - idna==3.11
      - jiter==0.12.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==1.1.0
      - langchain-classic==1.0.0
      - langchain-community==0.4.1
      - langchain-core==1.1.0
      - langchain-ollama==1.0.0
      - langchain-openai==1.1.0
      - langchain-text-splitters==1.0.0
      - langgraph==1.0.3
      - langgraph-checkpoint==3.0.1
      - langgraph-prebuilt==1.0.5
      - langgraph-sdk==0.2.10
      - langsmith==0.4.47
      - marshmallow==3.26.1
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - ollama==0.6.1
      - openai==2.8.1
      - orjson==3.11.4
      - ormsgpack==1.12.0
      - pipdeptree==2.30.0
      - propcache==0.4.1
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - python-dotenv==1.2.1
      - python-multipart==0.0.20
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.44
      - starlette==0.50.0
      - tenacity==9.1.2
      - tiktoken==0.12.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - xxhash==3.6.0
      - yarl==1.22.0
      - zstandard==0.25.0
prefix: /home/vishal/miniconda3/envs/dap
